# This file was automatically generated by SWIG
package KRISP;

use vars qw (@VERSOIN @EXPORT);

require Exporter;
require DynaLoader;

@ISA = qw(Exporter DynaLoader);
$VERSION = "1.1.0";

package KRISP;
bootstrap KRISP;
package KRISP;

@EXPORT = qw(krisp_open_pl krisp_search_pl krisp_close_pl krisp_version_pl krisp_uversion_pl krisp_error_pl);

sub new {
	my $self = {};

	return bless $self;
}

sub krisp_version {
	my $self = shift if ref ($_[0]);

	return krisp_version_pl ();
}

sub krisp_uversion {
	my $self = shift if ref ($_[0]);

	return krisp_uversion_pl ();
}

sub krisp_error {
	my $self = shift if ref ($_[0]);

	return krisp_error_pl ();
}

sub krisp_open {
	my $self = shift if ref ($_[0]);
	my ($datafile) = @_;
	my $r;

	$r = krisp_open_pl ($datafile);

	return "" if ( $r == NULL );

	return $r;
}

sub krisp_search {
	my $self = shift if ref ($_[0]);
	my ($dbh, $host) = @_;
	my $data, @d;
	my $ret, @ars;

	@ars = qw (key ip netmask network broadcast icode iname gcode gname gcity);

	$data = krisp_search_pl ($dbh, $host);

	return "" if ( ! $data );

	@d = split /:/, $data;

	for my $i ( 0 .. 9 ) {
		$ret->{"$ars[$i]"} = $d[$i];
	}

	return $ret;
}

sub krisp_close {
	my $self = shift if ref ($_[0]);
	my ($dbh) = @_;

	krisp_close_pl ($dbh);
}

1;
